name: deploy release

env:
  BRANCH: release

on:
  push:
    branches:
      - "${{ env.BRANCH }}"
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: build and deploy
    env:
      framework: 'net6.0'
      config: 'Release'
      output: './publish'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - run: dotnet publish -c $config -f $framework -o $output
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{env.output}}/wwwroot
        destination_dir: ${{ env.BRANCH }}
        publish_branch: pages
        enable_jekyll: false
