name: deploy nightly

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      BRANCH: nightly
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      
      - name: add target
        run: rustup target add wasm32-unknown-unknown
        
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: install cargo-update
        run: cargo install cargo-update
        continue-on-error: true
      
      - name: install trunk
        run: cargo install trunk
        continue-on-error: true
        
      - name: update cargo tools
        run: cargo install-update --all

      - run: trunk build --release --public-url "$REPOSITORY_NAME/$BRANCH/"
        working-directory: xengram
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: xengram/dist
          publish_branch: pages
          destination_dir: ${{ env.BRANCH }}
          enable_jekyll: false
