name: deploy

on:
  pull_request:
    branches:
      - "nightly"
  push:
    branches:
      - "nightly"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: add target
        run: rustup target add wasm32-unknown-unknown
      
      - name: install trunk
        run: cargo install trunk

      - run: trunk build --release --public-url "${{ REPOSITORY_NAME }}/nightly/"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: pages
          destination_dir: nightly
          enable_jekyll: false