name: deploy beta

on:
  pull_request:
    branches:
      - "beta"
  push:
    branches:
      - "beta"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      DESTINATION_DIR: beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: add target
        run: rustup target add wasm32-unknown-unknown
      
      - name: install trunk
        run: cargo install trunk

      - run: trunk build --release --public-url "$REPOSITORY_NAME/$DESTINATION_DIR/"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: pages
          destination_dir: ${{ env.DESTINATION_DIR }}
          enable_jekyll: false
